// <auto-generated />
using System;
using HeroAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeroAPI.Migrations
{
    [DbContext(typeof(HeroAPIContext))]
    partial class HeroAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HeroAPI.Models.Ability", b =>
                {
                    b.Property<int>("AbilityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbilityID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbilityID");

                    b.ToTable("Abilities");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Ability");
                });

            modelBuilder.Entity("HeroAPI.Models.Hero", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Ability1ID")
                        .HasColumnType("int");

                    b.Property<int?>("Ability2ID")
                        .HasColumnType("int");

                    b.Property<int>("Armor")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PrimaryFireID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SecondaryFireID")
                        .HasColumnType("int");

                    b.Property<int>("Shield")
                        .HasColumnType("int");

                    b.Property<int?>("UltimateID")
                        .HasColumnType("int");

                    b.HasKey("Name");

                    b.HasIndex("Ability1ID");

                    b.HasIndex("Ability2ID");

                    b.HasIndex("PrimaryFireID");

                    b.HasIndex("SecondaryFireID");

                    b.HasIndex("UltimateID");

                    b.ToTable("Heroes");
                });

            modelBuilder.Entity("HeroAPI.Models.Weapon", b =>
                {
                    b.Property<int>("WeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeaponID"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeaponID");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("HeroAPI.Models.Standard", b =>
                {
                    b.HasBaseType("HeroAPI.Models.Ability");

                    b.Property<int?>("Cooldown")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Standard");
                });

            modelBuilder.Entity("HeroAPI.Models.Ulimate", b =>
                {
                    b.HasBaseType("HeroAPI.Models.Ability");

                    b.Property<int?>("Cost")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Ulimate");
                });

            modelBuilder.Entity("HeroAPI.Models.Hero", b =>
                {
                    b.HasOne("HeroAPI.Models.Standard", "Ability1")
                        .WithMany()
                        .HasForeignKey("Ability1ID");

                    b.HasOne("HeroAPI.Models.Standard", "Ability2")
                        .WithMany()
                        .HasForeignKey("Ability2ID");

                    b.HasOne("HeroAPI.Models.Weapon", "PrimaryFire")
                        .WithMany()
                        .HasForeignKey("PrimaryFireID");

                    b.HasOne("HeroAPI.Models.Weapon", "SecondaryFire")
                        .WithMany()
                        .HasForeignKey("SecondaryFireID");

                    b.HasOne("HeroAPI.Models.Ulimate", "Ultimate")
                        .WithMany()
                        .HasForeignKey("UltimateID");

                    b.Navigation("Ability1");

                    b.Navigation("Ability2");

                    b.Navigation("PrimaryFire");

                    b.Navigation("SecondaryFire");

                    b.Navigation("Ultimate");
                });
#pragma warning restore 612, 618
        }
    }
}
